version: '3'

services:
  db:
    restart: always
    image: postgres
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
    ports:
      - 5432:5432
    container_name: db_postgres
  redis:
    image: "redis:7-alpine"
    ports:
      - 6379:6379
  web:
    restart: always
    stdin_open: true
    tty: true 
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:cached
      - gem_cache:/gems
    build: .
    entrypoint: sh ./docker-entrypoint.sh
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
      DB_PORT: 3318
      DB_USER: blog
      DB_PASSWORD: blog
volumes:
  gem_cache:
  db_value:
