default: &default
  pool: 10
  encoding: unicode
  host: db
  username: blog
  password: blog
  adapter: postgresql

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  pool: 10
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  adapter: postgresql
  database: postgresql
